name: Publish docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }}  | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - run: docker build -t redpelicans/puppeteer . 
      - run: docker push redpelicans/puppeteer 

